### PR TITLE
Issue 5558

### LINKED ISSUE #5558: Do not allow realtime table creation if timeColumnName is null
A realtime table doesn't work in Pinot without a timeColumnName defined in the table config. However, we do no validation to ensure that the table config we are creating has a valid time column name. 
Add validations to
1) check that timeColumnName is defined in the table config being uploaded/updated
2) ensure it is present in  schema

### PR DESCRIPTION
**Pull request by Sreemanth**
## Description
Fixed #5558 . Moved validation to `TableConfigUtils.validate()`

### CODE REVIEW

File: pinot-common/src/main/java/org/apache/pinot/common/utils/config/TableConfigUtils.java [hunk 1]
```diff
@@ -211,6 +211,10 @@ private static void validateFieldConfigList(TableConfig tableConfig) {
   private static void validateValidationConfig(TableConfig tableConfig) {
     SegmentsValidationAndRetentionConfig validationConfig = tableConfig.getValidationConfig();
     if (validationConfig != null) {
+      String timeColumnName = validationConfig.getTimeColumnName();
+      if(timeColumnName == null) {
+        throw new IllegalStateException("Must provide valid timeColumnName in tableConfig");
+      }
```
Comment (Jackie-Jiang) [inline pinot-common/src/main/java/org/apache/pinot/common/utils/config/TableConfigUtils.java:217]: Only force time column for real-time table, and please fix the format
```suggestion
      if (tableConfig.getTableType() == TableType.REALTIME && validationConfig.getTimeColumnName() == null) {
        throw new IllegalStateException("Must provide time column in real-time table config");
      }
```
